version: 2.1

orbs:
  codecov: codecov/codecov@5

jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Install package
          command: pip install -e .

      - run:
          name: Install testing tools
          command: pip install pytest pytest-cov

      - run:
          name: Run tests and collect coverage
          command: pytest --cov --cov-branch --cov-report=xml

      - codecov/upload:
          token: CODECOV_TOKEN
          slug: hcherkaoui/agoralearn
          flags: unittests

workflows:
  version: 2
  build-test:
    jobs:
      - build
